package application;

import javafx.fxml.FXML;


import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.scene.Node;

import javafx.event.ActionEvent;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.stage.Stage;

import java.awt.Button;
import java.io.IOException;
import Backend.JobPortal;

public class LoginController 
{
	private JobPortal jp;
	
	private String type;
	
	private Stage stage;
	 private Scene scene;
	 private Parent root;
	
	@FXML
	private TextField usernameField;
	@FXML
	private TextField passwordShown;
	@FXML
	private PasswordField passwordHidden;
	@FXML
	private CheckBox cb;
	@FXML
	private CheckBox cb2;
	@FXML
	private Button signupBtn;
	// Event Listener on Button.onAction
	
	public LoginController() 
	{
		jp = JobPortal.getInstance(); // Initialize JobPortal (Example)
		//jp=new JobPortal();
    }
	@FXML
	public void btnLoginClicked(ActionEvent event)
	{
		// TODO Autogenerated
		String username=usernameField.getText();
		String password=passwordHidden.getText();
		type = cb2.isSelected() ? "Employee" : "JobSeeker";
		if(jp.TryForLogin(username, password,type))
		{
			//System.out.println("Login Successfuly.........");
			//showAlert(Alert.AlertType.INFORMATION,"Success","Login successful");
			if(type.equals("JobSeeker"))
			{
				try {
					root = FXMLLoader.load(getClass().getResource("MainSceneJS.fxml"));
					stage = (Stage)((Node)event.getSource()).getScene().getWindow();
					scene = new Scene(root);
					stage.setScene(scene);
					stage.show();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
			else
			{
				try {
					root = FXMLLoader.load(getClass().getResource("Employer.fxml"));
					stage = (Stage)((Node)event.getSource()).getScene().getWindow();
					scene = new Scene(root);
					stage.setScene(scene);
					stage.show();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
			
	    }
		else
		{
			   showAlert(Alert.AlertType.ERROR, "Invalid Username", "Pass or username invalid");
			//System.out.println("Pass or username Invalid..");
			usernameField.clear();
			passwordHidden.clear();
			
		}
		
	}
	
	@FXML
	public void changeVisibility(ActionEvent event)
	{
		if(cb.isSelected())
		{
			passwordShown.setText(passwordHidden.getText());
			passwordShown.setVisible(true);
			passwordHidden.setVisible(false);
			return;
		}
		else
		{
			passwordHidden.setText(passwordShown.getText());
			passwordHidden.setVisible(true);
			passwordShown.setVisible(false);
		}
		
	}
	@FXML
	public void changeToSignupScene(ActionEvent event)
	{
		try {
			root = FXMLLoader.load(getClass().getResource("Signup.fxml"));
			stage = (Stage)((Node)event.getSource()).getScene().getWindow();
			scene = new Scene(root);
			stage.setScene(scene);
			stage.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	private void showAlert(Alert.AlertType alerttype,String title,String message)
	{
	   	Alert alert=new Alert(alerttype);
	   	alert.setTitle(title);
	   	alert.setHeaderText(null);
	   	alert.setContentText(message);
	   	alert.showAndWait();
	}
	
}
